#!/usr/bin/env bash
# Writes web/config.js from the deployed stack's outputs.
#
# Same shape and the same reasoning as `./scripts/http-requests.sh`: the committed thing is a
# template, the generated thing holds real ids and an API key and is git-ignored. It is a
# separate script rather than another `fill` in that one because the output is JavaScript, not
# a `.http` file, and because the page is useful to regenerate on its own — the .http
# collections need a client secret this page must never see.
#
#   ./scripts/web-config.sh
#
# Then serve the page (the port is in the Cognito callback URL, so it is not negotiable):
#   python3 -m http.server 5173 --directory web
set -euo pipefail

PROFILE="${AWS_PROFILE:-ai-playground}"
STACK="${STACK_NAME:-TravelAssistantStack}"
HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
ORIGIN="http://localhost:5173"

out() {
  aws cloudformation describe-stacks --stack-name "$STACK" --profile "$PROFILE" \
    --query "Stacks[0].Outputs[?OutputKey=='$1'].OutputValue" --output text
}

echo "==> reading stack outputs"
HOSTED_UI=$(out HostedUiDomain)
WEB_CLIENT_ID=$(out WebClientId)
API_URL=$(out ApiUrl)
API_KEY_ID=$(out ApiKeyId)

API_KEY=$(aws apigateway get-api-key --profile "$PROFILE" \
  --api-key "$API_KEY_ID" --include-value --query 'value' --output text)

cat > "$HERE/web/config.js" <<EOF
// GENERATED by ./scripts/web-config.sh — git-ignored. Do not edit; regenerate after a deploy.
//
// The API key below is public by construction: it is sent by a browser, so anyone holding the
// browser holds the key. It is here because it attaches the request to the usage plan whose
// 100-requests/day quota is the budget control, not because it authenticates anything.
window.APP_CONFIG = {
  hostedUi: '${HOSTED_UI}',
  clientId: '${WEB_CLIENT_ID}',
  // Must match the stack's callbackUrls exactly, trailing slash included.
  redirectUri: '${ORIGIN}/',
  apiUrl: '${API_URL}',
  apiKey: '${API_KEY}',
};
EOF

chmod 600 "$HERE/web/config.js"

echo "==> wrote web/config.js (git-ignored, mode 600)"
echo "    hosted UI : $HOSTED_UI"
echo "    client    : $WEB_CLIENT_ID (public, no secret)"
echo "    api       : $API_URL"
echo
echo "Serve it on the port the callback URL names:"
echo "  python3 -m http.server 5173 --directory web"
